<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com and you will be sent a copy immediately.
 *
 * PHP version 7.3.17
 *
 * @category Templates
 * @package  Magento
 * @author   Bertozzi Matteo <bertozzi@i-ways.net>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License 3.0
 * @link     https://www.i-ways.net
 */
$moduleName = 'Iways_PaypalInstalmentsBanners';
$logoImage = $block->getData('logo_image')
          ?: $block->getViewFileUrl($moduleName . '::images/logo_hq.png');
?>
<div class="paypal-instalments-logo">
    <a href="<?= $block->escapeHtml($block->getData('target_url')) ?>"
       target="_blank" title="<?= $block->escapeHtml(__('PayPal Credit')) ?>">
        <img src="<?= $block->escapeHtml($logoImage) ?>"
             alt="<?= $block->escapeHtml(__('PayPal Credit')) ?>">
    </a>
</div>